#!/bin/bash

. ./disable-power-saving.sh

function reload_module() {
        rmmod dm-crypt
        insmod modules/$1/dm-crypt.ko || exit 1
}

function usage() {
	echo "$0 <randseed> </absolute/path/to/fio/binary>" >&2
}

test $# -gt 1 || {
        usage
	exit 1
}

BSIZE_LIST="512 2k 4k 8k 16k 32k 64k 128k"

ZEROSIZE=$((3 * 1024 * 1024 * 1024 / 512))

ITERATIONS=20

SIZE=$((3 * 1024 * 1024 * 1024))

disable_cpu_throttling

for prefix in no_patch no_percpu use_per_bio_data dont_alloc_to_remove_io_pending  ; do
        reload_module $prefix

	cd 1

	modelist="read"
	for bsize in $BSIZE_LIST; do
		COUNT=$((SIZE / bsize))
		./test-zero.sh --debug --randseed $1 --iterations $ITERATIONS --job 0000_job_default \
			--jobdir /home/okozina/dmcrypt-tests/1/jobs \
			--log /home/okozina/logs/test_zero/${modelist/ /_}_seq/bsize_$bsize/log_"$prefix" \
			--modelist "$modelist" --ioengine libaio --fio $2 --ramp_time 0 --numjobs 1 \
			--bsize $bsize --zerosize $ZEROSIZE --number_ios $COUNT
	done

	modelist="write"
	for bsize in $BSIZE_LIST; do
		COUNT=$((SIZE / bsize))
		./test-zero.sh --debug --randseed $1 --iterations $ITERATIONS --job 0000_job_default \
			--jobdir /home/okozina/dmcrypt-tests/1/jobs \
			--log /home/okozina/logs/test_zero/${modelist/ /_}_seq/bsize_$bsize/log_"$prefix" \
			--modelist "$modelist" --ioengine libaio --fio $2 --ramp_time 0 --numjobs 1 \
			--bsize $bsize --zerosize $ZEROSIZE --number_ios $COUNT
	done

	cd ..
done

enable_cpu_throttling
